# Generated by Django 3.2 on 2021-05-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content_head1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_head2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_head3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='heading1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='heading2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='heading3',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(blank=True),
        ),
    ]
